name: Build and Push Docker Image
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ ECR.ECR_URL }}
      - run: docker build -t ${{ ECR.ECR_NAME }} .
      - run: docker tag "${{ ECR.ECR_NAME }}:latest" "${{ ECR.ECR_URL }}/${{ ECR.ECR_NAME }}:latest"
      - run: docker push "${{ ECR.ECR_URL }}/${{ ECR.ECR_NAME }}:latest"
